<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_email_login</name>
   <tag></tag>
   <elementGuidId>32d47e59-0e96-498d-ac80-38f27dfaedc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-89&quot;)[count(. | //input[@id = 'input-89' and @type = 'text']) = count(//input[@id = 'input-89' and @type = 'text'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-89</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2483f305-69db-426f-911b-0945d1c7b0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-89</value>
      <webElementGuid>3ad6039c-4561-45f8-b819-ec1c3c90c6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a47047d-27b8-4625-800d-8713fd35d07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-89&quot;)</value>
      <webElementGuid>7495725c-6f95-4919-af93-d07311277d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-89']</value>
      <webElementGuid>376771f2-14b3-416e-9835-be2c95824dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>1683077c-8bdc-499d-b590-dda4aab5fb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9d592491-18d2-413a-8462-6d481459266f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-89' and @type = 'text']</value>
      <webElementGuid>be23f37c-9f28-4f51-89da-9901d1e126ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
