<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_nama_lengkap_register</name>
   <tag></tag>
   <elementGuidId>3be267ac-a0f8-4e65-9295-58b16aa902a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-50&quot;)[count(. | //input[@id = 'input-50' and @type = 'text']) = count(//input[@id = 'input-50' and @type = 'text'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-50</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a37a4fe3-3a7f-442f-a0b3-ecef1b82d04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-50</value>
      <webElementGuid>3a2870be-06ed-4d38-a832-f63992d498ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05192f46-f3eb-4106-a4f2-fdd5b17b4f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-50&quot;)</value>
      <webElementGuid>d64a6db2-3dd2-4b96-a0ae-fee6e73d2608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-50']</value>
      <webElementGuid>f8334752-f65e-440a-ab79-7be8daf54abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>577749e8-7d4f-435d-822f-6c897808f858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4894cde-201f-46e9-8738-c0b061250f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-50' and @type = 'text']</value>
      <webElementGuid>716dbd57-2bcb-4b5b-a1a4-6a828d7b85d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
