<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_password_login</name>
   <tag></tag>
   <elementGuidId>5fbefe74-820f-46f2-9e80-d1fb046ca9ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'input-92']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-92</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b14d61-35f7-4267-8e55-3ef5638e931c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-92</value>
      <webElementGuid>5b516412-1982-400f-bd8f-31ba02e7cc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4de50df1-f190-4527-be08-8815aea0575c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-92&quot;)</value>
      <webElementGuid>cf218661-175e-46ab-a130-b3abde16718d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-92']</value>
      <webElementGuid>05626ba6-88a9-4590-accb-c0eb74105d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>645aed65-b5cc-4927-b513-e0a35267ebcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>24008264-e70a-4300-91d2-7251a4d83ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-92' and @type = 'text']</value>
      <webElementGuid>064774eb-4a07-40d3-8381-80c2de597f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
